apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-gjmz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-gjmz
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-gjmz
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-gjmz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-gjmz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vebq-tenant/rhtap-demo-app/hacbs-test-project-gjmz@sha256:42ea901e0ecc9b38271aabe56c801e0bc88ab85e2aa2cd8ffa82b544db410360
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
